### ISSUE TITLE
API for submitting license corrections

### ISSUE THREAD

**Issue by bootstraponline** [versioneye/versioneye-api#4]
The license database is incomplete. Often large amounts of projects are marked as unknown even when there's a clear license. This is problematic when dealing with GPL code that is marked as unknown. For example:
- https://www.versioneye.com/java/com.ximpleware:vtd-xml/2.11

I'd like some way to crowd source the integrity checking of the database so that people can submit corrections via an API.

**Comment by bootstraponline** [comment]
It looks like that example is already fixed. I have a bunch more unknowns from my project so the original point stands.

**Comment by bootstraponline** [comment]
It'd be also nice to guess the license because if `v2.11` is unknown and `v2.12` is detected as GPL then that'd be very good to know, even if we aren't 100% sure.

**Comment by bootstraponline** [comment]
Related: https://bitbucket.org/versioneye/versioneye/issues/274/how-to-report-for-missing-licenses

**Comment by reiz** [comment]
It's implemented now. See here for more details: https://blog.versioneye.com/2017/01/18/suggest-new-licenses/
