### ISSUE TITLE
Implementation Note are not displayed

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye-api#7]
Somehow the new SwaggerUI does not display the implementation notes. Here for example we have some additional notes with a link to further documentation. 

<img width="1023" alt="screen shot 2017-02-02 at 19 25 16" src="https://cloud.githubusercontent.com/assets/652130/22562564/64894294-e97d-11e6-8d45-7dbcc88ea556.png">

On the swagger UI page this note does not show up anymore. It showed up in the last swaggerUI version we used. /cc @timgluz

**Comment by timgluz** [comment]
Ok, it's seems that `notes` field has deprecated in the favor of `detail`: https://github.com/ruby-grape/grape-swagger/blob/master/UPGRADING.md#upgrading-to--0102

New usage:
https://github.com/ruby-grape/grape-swagger#specify-endpoint-details

**Comment by reiz** [comment]
@timgluz Thanks for the hint. It works now.
